version: "3.9"
services:
  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/betreut-zu-hause/loyacrm/frontend:staging}
  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/betreut-zu-hause/loyacrm/backend:staging}
  nginx:
    ports:
      - "8080:80"
